spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Chhal_Kayen_Binatna
    username: postgres
    password: khalil
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8090

#logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG