spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Chhal_Kayen_Binatna
    username: postgres
    password: khalil
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8090